version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: roots
      MYSQL_PASSWORD: rootroot
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3311:3306"
    command: mysqld --character_set_server=utf8
    volumes:
      - ./db_data:/var/lib/mysql